// Fictional demo content. Every brand, product, person and article here is
// invented for development; none of it describes a real company or product.

export const categories = [
  { slug: 'ai-gadgets', name: 'AI Gadgets', color: '#5B5BD6', icon: 'sparkles', featured: true, description: 'Devices that listen, see and think on their own — from pocket translators to desk robots.' , zh: { name: 'AI 智能產品', description: '會聆聽、觀察和思考的裝置——由袖珍翻譯機到桌面機械人。' } },
  { slug: 'smart-home', name: 'Smart Home', color: '#0E9384', icon: 'house', featured: true, description: 'Lights, locks, sensors and hubs that make a home run itself.' , zh: { name: '智能家居', description: '讓家居自動運作的燈光、門鎖、感應器和中樞。' } },
  { slug: 'gaming', name: 'Gaming', color: '#C4320A', icon: 'gamepad-2', featured: true, description: 'Controllers, handhelds and accessories for players who care about the details.' , zh: { name: '遊戲', description: '為講究細節的玩家而設的手掣、掌機和配件。' } },
  { slug: 'audio', name: 'Audio', color: '#344054', icon: 'headphones', featured: true, description: 'Headphones, earbuds and speakers tuned for people who really listen.' , zh: { name: '音響', description: '為認真聆聽的人調校的耳機、耳筒和喇叭。' } },
  { slug: 'photography', name: 'Photography', color: '#B54708', icon: 'camera', featured: true, description: 'Cameras, lenses, drones and the gear that gets the shot.' , zh: { name: '攝影', description: '相機、鏡頭、航拍機，以及助你拍出好照片的裝備。' } },
  { slug: 'wearables', name: 'Wearables', color: '#7A2E0E', icon: 'watch', featured: true, description: 'Watches, rings and bands that track, notify and look good doing it.' , zh: { name: '穿戴裝置', description: '能追蹤、會提示，而且好看的手錶、指環和手帶。' } },
  { slug: 'travel', name: 'Travel', color: '#1570EF', icon: 'plane', featured: true, description: 'Carry-on friendly gear that makes getting there easier.' , zh: { name: '旅遊', description: '符合手提行李規定、令旅程更輕鬆的裝備。' } },
  { slug: 'fitness', name: 'Fitness', color: '#DC6803', icon: 'dumbbell', featured: true, description: 'Smart training tools for home workouts and serious athletes.' , zh: { name: '健身', description: '適合居家訓練和認真運動人士的智能訓練工具。' } },
  { slug: 'kitchen', name: 'Kitchen', color: '#9E165F', icon: 'chef-hat', featured: true, description: 'Connected appliances and clever tools for better cooking.' , zh: { name: '廚房', description: '令烹飪更出色的智能電器和實用工具。' } },
  { slug: 'office', name: 'Office', color: '#475467', icon: 'briefcase', featured: true, description: 'Desk setups, keyboards and accessories for focused work.' , zh: { name: '辦公', description: '助你專心工作的桌面佈置、鍵盤和配件。' } },
  { slug: 'outdoor', name: 'Outdoor', color: '#3B7C0F', icon: 'mountain', featured: true, description: 'Tough, packable tech for trails, camps and everything off-grid.' , zh: { name: '戶外', description: '為山徑、營地和無網絡環境而設的耐用輕便科技產品。' } },
  { slug: 'automotive', name: 'Automotive', color: '#1D2939', icon: 'car', featured: true, description: 'Dash cams, chargers and upgrades for the car.' , zh: { name: '汽車', description: '行車記錄器、充電器和車內升級配件。' } },
  { slug: 'productivity', name: 'Productivity', color: '#6941C6', icon: 'list-checks', featured: false, description: 'Tools that help you plan, capture and get things done.' , zh: { name: '效率工具', description: '幫你計劃、記錄和完成工作的工具。' } },
  { slug: 'health-wellness', name: 'Health & Wellness', color: '#E31B54', icon: 'heart-pulse', featured: false, description: 'Sleep, air, posture and recovery tech.' , zh: { name: '健康生活', description: '睡眠、空氣質素、坐姿和恢復相關的科技產品。' } },
  { slug: 'eco-tech', name: 'Eco Tech', color: '#027A48', icon: 'leaf', featured: false, description: 'Solar, repairable and low-waste gadgets.' , zh: { name: '環保科技', description: '太陽能、可維修和低浪費的電子產品。' } },
  // subcategories
  { slug: 'headphones', name: 'Headphones', parent: 'audio', color: '#344054', icon: 'headphones', description: 'Over-ear and on-ear headphones.' , zh: { name: '頭戴式耳機', description: '頭戴式及貼耳式耳機。' } },
  { slug: 'speakers', name: 'Speakers', parent: 'audio', color: '#344054', icon: 'speaker', description: 'Portable and home speakers.' , zh: { name: '喇叭', description: '便攜及家用喇叭。' } },
  { slug: 'smart-lighting', name: 'Smart Lighting', parent: 'smart-home', color: '#0E9384', icon: 'lamp', description: 'Bulbs, lamps and light strips.' , zh: { name: '智能照明', description: '燈泡、檯燈和燈帶。' } },
  { slug: 'home-security', name: 'Home Security', parent: 'smart-home', color: '#0E9384', icon: 'shield', description: 'Cameras, locks and sensors.' , zh: { name: '家居保安', description: '鏡頭、門鎖和感應器。' } },
  { slug: 'desk-setup', name: 'Desk Setup', parent: 'office', color: '#475467', icon: 'monitor', description: 'Stands, lights and desk accessories.' , zh: { name: '桌面佈置', description: '顯示器支架、燈具和桌面配件。' } },
  { slug: 'keyboards', name: 'Keyboards', parent: 'office', color: '#475467', icon: 'keyboard', description: 'Mechanical and low-profile keyboards.' , zh: { name: '鍵盤', description: '機械式及薄身鍵盤。' } },
  { slug: 'drones', name: 'Drones', parent: 'photography', color: '#B54708', icon: 'plane', description: 'Camera drones and accessories.' , zh: { name: '航拍機', description: '航拍機及配件。' } },
]

// owner: which demo seller owns the brand (seller1..seller3) or null (editorial).
export const brands = [
  { slug: 'halden-audio', name: 'Halden Audio', owner: 'seller1', tagline: 'Quiet engineering for loud music.', website: 'https://halden-audio.example.com', description: 'Halden Audio builds headphones and speakers around one idea: remove everything that gets between you and the recording. Small team, long warranties, replaceable parts.' },
  { slug: 'cinder-audio', name: 'Cinder Audio', owner: null, tagline: 'Speakers with a campfire glow.', website: 'https://cinder-audio.example.com', description: 'Cinder makes warm-sounding portable speakers with fabric shells and ambient lighting, designed for evenings rather than parties.' },
  { slug: 'veloce-labs', name: 'Veloce Labs', owner: 'seller2', tagline: 'Training data, not guesswork.', website: 'https://velocelabs.example.com', description: 'Veloce Labs designs sensors and smart equipment for athletes who want numbers they can trust.' },
  { slug: 'lumen-and-oak', name: 'Lumen & Oak', owner: 'seller1', tagline: 'Light that follows the sun.', website: 'https://lumenandoak.example.com', description: 'Lumen & Oak combines solid wood with tunable LEDs to make lamps that shift color through the day.' },
  { slug: 'parsec-robotics', name: 'Parsec Robotics', owner: null, tagline: 'Small robots, big patience.', website: 'https://parsecrobotics.example.com', description: 'Parsec builds friendly desktop and home robots powered by on-device AI, with privacy switches you can physically flip.' },
  { slug: 'driftline', name: 'Driftline', owner: 'seller3', tagline: 'Carry less. See more.', website: 'https://driftline.example.com', description: 'Driftline makes modular travel bags and organizers that fit every major airline\'s carry-on limits.' },
  { slug: 'kestrel-optics', name: 'Kestrel Optics', owner: null, tagline: 'Glass you can rely on.', website: 'https://kestreloptics.example.com', description: 'Kestrel Optics designs compact cameras, lenses and drones for travelling photographers.' },
  { slug: 'moonforge', name: 'Moonforge', owner: null, tagline: 'Hardware for the long session.', website: 'https://moonforge.example.com', description: 'Moonforge builds controllers and handheld accessories with hall-effect sticks and swappable everything.' },
  { slug: 'tallow-kitchen', name: 'Tallow Kitchen Co.', owner: 'seller2', tagline: 'Precise heat, simple controls.', website: 'https://tallowkitchen.example.com', description: 'Tallow makes connected kitchen tools with real buttons and apps that are optional, not required.' },
  { slug: 'quillwork', name: 'Quillwork', owner: null, tagline: 'Tools for deep work.', website: 'https://quillwork.example.com', description: 'Quillwork designs e-paper notebooks and focus tools for people who want fewer notifications.' },
  { slug: 'ridgeback-outdoor', name: 'Ridgeback Outdoor', owner: 'seller3', tagline: 'Built for the long way round.', website: 'https://ridgebackoutdoor.example.com', description: 'Ridgeback makes solar power, lighting and navigation gear for multi-day trips.' },
  { slug: 'voltra-motive', name: 'Voltra Motive', owner: null, tagline: 'Upgrades for every car.', website: 'https://voltramotive.example.com', description: 'Voltra makes dash cams, chargers and in-car accessories that install in minutes.' },
  { slug: 'sable-wearables', name: 'Sable Wearables', owner: null, tagline: 'Health tracking you forget you\'re wearing.', website: 'https://sablewearables.example.com', description: 'Sable designs lightweight rings and bands with multi-week battery life.' },
  { slug: 'nimbus-home', name: 'Nimbus Home', owner: null, tagline: 'The quiet smart home.', website: 'https://nimbushome.example.com', description: 'Nimbus makes sensors, locks and hubs that work locally, even when the internet does not.' },
  { slug: 'fernhill-wellness', name: 'Fernhill Wellness', owner: null, tagline: 'Rest is a skill.', website: 'https://fernhillwellness.example.com', description: 'Fernhill builds sleep and recovery devices backed by published research.' },
  { slug: 'orbital-desk', name: 'Orbital Desk', owner: 'seller1', tagline: 'A better desk in one afternoon.', website: 'https://orbitaldesk.example.com', description: 'Orbital makes monitor arms, docks and desk lights designed to work together.' },
  { slug: 'petrichor-tech', name: 'Petrichor Tech', owner: null, tagline: 'Tech that gives back.', website: 'https://petrichortech.example.com', description: 'Petrichor designs repairable, solar-assisted electronics from recycled materials.' },
  { slug: 'grainfield-camera', name: 'Grainfield Camera Co.', owner: null, tagline: 'Film feel, digital speed.', website: 'https://grainfieldcamera.example.com', description: 'Grainfield makes compact digital cameras with physical dials and film-inspired color profiles.' },
  { slug: 'tessellate', name: 'Tessellate', owner: null, tagline: 'AI that stays on your device.', website: 'https://tessellate.example.com', description: 'Tessellate builds pocket AI devices that translate, transcribe and summarize without a cloud account.' },
  { slug: 'brightwater-gear', name: 'Brightwater Gear', owner: 'seller3', tagline: 'Clean water anywhere.', website: 'https://brightwatergear.example.com', description: 'Brightwater makes UV purifiers and smart bottles for travellers and hikers.' },
  { slug: 'pocketwise', name: 'Pocketwise', owner: null, tagline: 'Everything, one pocket.', website: 'https://pocketwise.example.com', description: 'Pocketwise designs slim chargers, trackers and wallets.' },
  { slug: 'arclight-gaming', name: 'Arclight Gaming', owner: null, tagline: 'See the whole map.', website: 'https://arclightgaming.example.com', description: 'Arclight makes portable monitors and streaming gear for gamers on the move.' },
  { slug: 'hearth-and-byte', name: 'Hearth & Byte', owner: null, tagline: 'Smarter cooking, same kitchen.', website: 'https://hearthandbyte.example.com', description: 'Hearth & Byte builds countertop appliances with cameras and sensors that help you cook, not replace you.' },
]

// shape: which illustration to draw for the demo images.
// status defaults to published; seller products may use other workflow states.
export const products = [
  // Audio
  { name: 'Halden Arc Pro', brand: 'halden-audio', cats: ['audio', 'headphones'], price: 349, orig: 399, shape: 'headphones', hue: 220, tags: ['noise-cancelling', 'wireless', 'repairable'], sku: 'HAL-ARC-PRO', score: [8.9, 9, 8.5, 9, 8, 9], tagline: 'Noise-cancelling headphones with replaceable everything.', blurb: 'The Arc Pro pairs adaptive noise cancelling with a modular build: cushions, headband, battery and cable all swap out with a coin.', features: ['Adaptive noise cancelling with 4 mics per side', '50-hour battery, user-replaceable', 'Lossless over USB-C', 'Magnetic swappable ear cushions'], specs: { Weight: '285 g', Battery: '50 h (ANC on)', Connectivity: 'Bluetooth 5.4, USB-C audio', Warranty: '3 years' }, seller: 'seller1' },
  { name: 'Halden Pebble Buds', brand: 'halden-audio', cats: ['audio'], price: 179, shape: 'earbuds', hue: 200, tags: ['wireless', 'earbuds'], sku: 'HAL-PBL-01', tagline: 'Tiny earbuds with a case that fits a coin pocket.', blurb: 'Pebble Buds put a surprisingly large 10 mm driver in a shell smaller than a sugar cube.', features: ['10 mm graphene drivers', 'Wireless charging case', 'IPX5 sweat resistance', 'Multipoint pairing'], specs: { Battery: '8 h + 24 h case', Weight: '4.1 g per bud', Connectivity: 'Bluetooth 5.4' }, seller: 'seller1' },
  { name: 'Cinder Ember Speaker', brand: 'cinder-audio', cats: ['audio', 'speakers', 'outdoor'], price: 229, orig: 269, shape: 'speaker', hue: 25, tags: ['portable', 'waterproof'], sku: 'CIN-EMB-2', score: [8.4, 9.2, 7.8, 8.5, 8, 8.2], tagline: 'A portable speaker with a flickering ember light.', blurb: 'Ember throws 360° sound and a warm, flame-like glow that reacts to the music — built for evenings outside.', features: ['360° sound with passive bass radiator', 'Ember-effect ambient light', 'IP67 waterproof and floats', 'Party mode for up to 8 speakers'], specs: { Battery: '20 h', Weight: '780 g', Waterproofing: 'IP67' } },
  { name: 'Cinder Hearth Bookshelf Pair', brand: 'cinder-audio', cats: ['audio', 'speakers', 'smart-home'], price: 499, shape: 'speaker', hue: 30, tags: ['hi-fi', 'wifi'], tagline: 'Powered bookshelf speakers with built-in streaming.', blurb: 'A pair of walnut-finished speakers with an amp, DAC and streaming built in — plug in power and you are done.', features: ['Wi-Fi and AirPlay-style streaming', 'HDMI ARC for TVs', 'Room correction via phone mic', 'Real wood veneer'], specs: { Power: '2 × 60 W', Inputs: 'HDMI ARC, optical, USB-C, phono', Warranty: '2 years' } },
  { name: 'Halden Studio Monitor 5', brand: 'halden-audio', cats: ['audio', 'speakers', 'office'], price: 399, shape: 'speaker', hue: 210, tags: ['studio', 'hi-fi'], tagline: 'Desktop monitors flat enough to mix on.', blurb: 'Studio Monitor 5 gives creators an honest, flat response in a size that fits beside a laptop.', features: ['5" woven woofers', 'Adjustable room EQ', 'Balanced XLR inputs', 'Auto standby'], specs: { Response: '48 Hz – 22 kHz', Inputs: 'XLR, TRS, USB-C' }, seller: 'seller1' },
  // AI gadgets
  { name: 'Tessellate Lingo One', brand: 'tessellate', cats: ['ai-gadgets', 'travel'], price: 249, orig: 299, shape: 'phone', hue: 250, tags: ['translation', 'on-device-ai', 'offline'], sku: 'TES-LINGO-1', score: [9.1, 8.8, 9.2, 9.4, 8.7, 9], tagline: 'An offline pocket translator for 42 languages.', blurb: 'Lingo One runs its translation models entirely on the device, so it works on a plane, in the mountains and anywhere you would rather not upload a conversation.', features: ['Offline speech translation in 42 languages', 'Two-way conversation mode', 'Camera translation of signs and menus', 'No account required'], specs: { Battery: '2 days typical', Weight: '96 g', Storage: '64 GB', Connectivity: 'Wi-Fi, Bluetooth, optional eSIM' } },
  { name: 'Tessellate Minutes', brand: 'tessellate', cats: ['ai-gadgets', 'productivity', 'office'], price: 159, shape: 'charger', hue: 260, tags: ['transcription', 'on-device-ai'], tagline: 'A clip-on recorder that transcribes meetings privately.', blurb: 'Minutes records, transcribes and summarizes meetings on-device, then syncs text only when you ask it to.', features: ['On-device transcription', 'Speaker labels', 'Magnetic clip', 'Physical privacy switch'], specs: { Battery: '30 h recording', Weight: '28 g' } },
  { name: 'Parsec Pip Desk Robot', brand: 'parsec-robotics', cats: ['ai-gadgets', 'office'], price: 299, shape: 'robot', hue: 280, tags: ['robot', 'on-device-ai', 'privacy'], score: [8.2, 9.5, 7.6, 7.5, 8.1, 8.3], tagline: 'A desk companion that keeps you on schedule.', blurb: 'Pip reminds you to stand, tracks focus sessions and reacts to your mood — with the camera physically covered until you open it.', features: ['Expressive e-ink face', 'Focus timer and posture nudges', 'Mechanical camera shutter', 'Works without cloud account'], specs: { Weight: '410 g', Power: 'USB-C', Sensors: 'Camera, 2 mics, ToF' } },
  { name: 'Parsec Rover Home Assistant', brand: 'parsec-robotics', cats: ['ai-gadgets', 'smart-home', 'home-security'], price: 899, shape: 'robot', hue: 190, availability: 'preorder', tags: ['robot', 'security'], tagline: 'A rolling home robot that patrols while you are away.', blurb: 'Rover maps your home, checks on pets and sends a clip if something moves — then docks itself to charge.', features: ['Autonomous room mapping', 'Pet and person detection', 'Two-way audio', 'Self-docking'], specs: { Battery: '4 h patrol', Camera: '4K HDR', Weight: '3.2 kg' } },
  { name: 'Tessellate Glance Glasses', brand: 'tessellate', cats: ['ai-gadgets', 'wearables'], price: 449, shape: 'glasses', hue: 240, availability: 'coming_soon', tags: ['smart-glasses', 'on-device-ai'], tagline: 'Glasses that caption conversations in real time.', blurb: 'Glance shows live captions and translations in the corner of your vision, processed on a paired phone.', features: ['Live captions', 'Prescription-ready frames', '8-hour battery', 'Under 45 g'], specs: { Weight: '44 g', Battery: '8 h' } },
  // Smart home
  { name: 'Lumen & Oak Solstice Lamp', brand: 'lumen-and-oak', cats: ['smart-home', 'smart-lighting', 'office'], price: 189, orig: 229, shape: 'lamp', hue: 40, tags: ['circadian', 'lighting', 'wood'], score: [8.7, 9.4, 8.6, 8, 8.3, 8.8], tagline: 'A wooden desk lamp that follows daylight color.', blurb: 'Solstice shifts from crisp morning white to warm evening amber on its own, matched to your local sunrise and sunset.', features: ['Circadian color schedule', 'Solid oak base', 'Touch dimmer', 'Works without an app'], specs: { Brightness: '900 lm', 'Color temperature': '2200–6500 K', Materials: 'Oak, aluminium' }, seller: 'seller1' },
  { name: 'Lumen & Oak Halo Strip', brand: 'lumen-and-oak', cats: ['smart-home', 'smart-lighting'], price: 69, shape: 'bulb', hue: 50, tags: ['lighting'], tagline: 'A light strip with diffused, dot-free glow.', blurb: 'Halo uses a silicone diffuser so it looks like a continuous line of light instead of a row of dots.', features: ['Dot-free diffusion', 'Cuttable every 5 cm', 'Matter compatible'], specs: { Length: '2 m', Power: '24 W' }, seller: 'seller1' },
  { name: 'Nimbus Keystone Lock', brand: 'nimbus-home', cats: ['smart-home', 'home-security'], price: 279, shape: 'lock', hue: 170, tags: ['security', 'matter', 'local-control'], score: [8.5, 8, 8.7, 9, 8.2, 8.5], tagline: 'A smart lock that works when the Wi-Fi does not.', blurb: 'Keystone unlocks by fingerprint, phone or code, and every feature works locally with no cloud dependency.', features: ['Fingerprint reader', 'Local Matter control', 'Auto-lock and door sensor', 'Physical key backup'], specs: { Battery: '12 months (AA)', Connectivity: 'Thread, Bluetooth' } },
  { name: 'Nimbus Sense Hub', brand: 'nimbus-home', cats: ['smart-home'], price: 129, shape: 'hub', hue: 160, tags: ['matter', 'local-control', 'sensors'], tagline: 'A hub with air, sound and presence sensors built in.', blurb: 'Sense Hub runs your automations locally and adds room sensors for air quality, noise and presence.', features: ['Thread border router', 'Air quality and CO₂ sensing', 'Presence detection', 'Local automations'], specs: { Sensors: 'CO₂, VOC, temperature, humidity, mmWave', Power: 'USB-C' } },
  { name: 'Nimbus Watchpost Camera', brand: 'nimbus-home', cats: ['smart-home', 'home-security'], price: 149, orig: 179, shape: 'camera', hue: 180, tags: ['security', 'camera'], tagline: 'A weatherproof camera that records to its own storage.', blurb: 'Watchpost keeps recordings on an internal card, detects people and packages, and never requires a subscription.', features: ['2K HDR video', 'Local recording', 'Person and package detection', 'IP66 weatherproof'], specs: { Resolution: '2560 × 1440', Storage: '64 GB internal' } },
  // Gaming
  { name: 'Moonforge Tide Controller', brand: 'moonforge', cats: ['gaming'], price: 89, shape: 'controller', hue: 10, tags: ['hall-effect', 'wireless'], score: [8.8, 8.6, 9, 9.2, 8, 8.9], tagline: 'A controller with hall-effect sticks that never drift.', blurb: 'Tide uses magnetic hall-effect sensors for its sticks and triggers, so there is nothing to wear out.', features: ['Hall-effect sticks and triggers', 'Four remappable back buttons', 'Swappable stick caps', '40-hour battery'], specs: { Connectivity: '2.4 GHz, Bluetooth, USB-C', Weight: '248 g' } },
  { name: 'Moonforge Grip Dock', brand: 'moonforge', cats: ['gaming'], price: 59, shape: 'charger', hue: 15, tags: ['handheld', 'dock'], tagline: 'A dock and grip for handheld gaming PCs.', blurb: 'Grip Dock turns a handheld into a desktop setup with HDMI, Ethernet and charging, then folds into a travel grip.', features: ['4K60 HDMI out', '100 W passthrough', 'Folding grip mode'], specs: { Ports: 'HDMI 2.0, 3 × USB-A, Ethernet' } },
  { name: 'Arclight Vista 16 Portable Monitor', brand: 'arclight-gaming', cats: ['gaming', 'travel', 'office'], price: 329, orig: 379, shape: 'tablet', hue: 0, tags: ['monitor', 'portable'], score: [8.3, 8.4, 8.2, 8, 8.3, 8.6], tagline: 'A 16-inch 165 Hz monitor that fits in a laptop sleeve.', blurb: 'Vista 16 gives you a second screen for work and a fast one for games, powered by a single USB-C cable.', features: ['16" 2.5K 165 Hz panel', 'Single-cable USB-C', 'Built-in kickstand', 'HDR400'], specs: { Weight: '720 g', Panel: 'IPS, 2560 × 1600' } },
  { name: 'Arclight Stream Deck Mini', brand: 'arclight-gaming', cats: ['gaming', 'productivity'], price: 99, shape: 'keyboard', hue: 350, tags: ['streaming', 'macro'], tagline: 'Twelve programmable LCD keys for streamers.', blurb: 'Each key has its own tiny screen, so your scene switches and shortcuts are always labelled.', features: ['12 LCD keys', 'Multi-action macros', 'Profiles per app'], specs: { Connectivity: 'USB-C' } },
  // Photography
  { name: 'Kestrel Swift Drone', brand: 'kestrel-optics', cats: ['photography', 'drones', 'outdoor'], price: 649, orig: 749, shape: 'drone', hue: 30, tags: ['drone', '4k'], score: [9, 9, 8.8, 9.2, 8.5, 9.1], tagline: 'A sub-250 g drone with a 1-inch sensor.', blurb: 'Swift weighs under 250 g, so it avoids registration in many countries, yet carries a 1-inch sensor for clean evening footage.', features: ['1-inch 4K/60 sensor', 'Omnidirectional obstacle sensing', '38-minute flight time', 'Folds to phone size'], specs: { Weight: '249 g', 'Flight time': '38 min', Range: '10 km' } },
  { name: 'Grainfield F1 Compact', brand: 'grainfield-camera', cats: ['photography'], price: 899, shape: 'camera', hue: 35, tags: ['camera', 'film-simulation'], score: [8.6, 9.6, 8.4, 7.9, 8.5, 8.4], tagline: 'A pocket camera with real dials and film color.', blurb: 'The F1 has shutter, ISO and exposure dials on top and a set of film-inspired color profiles baked in.', features: ['24 MP APS-C sensor', 'Physical exposure dials', '12 film-style color profiles', 'Fixed 28 mm f/2.8 lens'], specs: { Weight: '390 g', Sensor: 'APS-C 24 MP' } },
  { name: 'Kestrel Trail Lens Kit', brand: 'kestrel-optics', cats: ['photography', 'travel'], price: 129, shape: 'lens', hue: 25, tags: ['phone-photography'], tagline: 'Clip-on macro and wide lenses for phones.', blurb: 'A magnetic mount and three glass lenses that turn a phone into a travel camera kit.', features: ['Magnetic mount', 'Macro, wide and tele lenses', 'Multi-coated glass'], specs: { Lenses: '10× macro, 16 mm wide, 58 mm tele' } },
  { name: 'Kestrel Slate Gimbal', brand: 'kestrel-optics', cats: ['photography'], price: 159, shape: 'gimbal', hue: 20, tags: ['stabilizer'], tagline: 'A foldable phone gimbal with face tracking.', blurb: 'Slate steadies phone video and keeps faces centered, then folds flat for a jacket pocket.', features: ['3-axis stabilization', 'Face tracking', 'Built-in tripod'], specs: { Battery: '10 h', Weight: '340 g' } },
  // Wearables
  { name: 'Sable Loop Ring', brand: 'sable-wearables', cats: ['wearables', 'health-wellness'], price: 299, shape: 'ring', hue: 30, tags: ['sleep-tracking', 'health'], score: [8.6, 9.1, 8.9, 7.8, 8.4, 8.8], tagline: 'A titanium ring that tracks sleep and recovery.', blurb: 'Loop measures heart rate, temperature and sleep stages, with a battery that lasts a week.', features: ['Sleep staging and readiness score', 'Skin temperature trends', '7-day battery', 'No subscription'], specs: { Weight: '4 g', Material: 'Titanium', Waterproofing: '100 m' } },
  { name: 'Sable Stride Band', brand: 'sable-wearables', cats: ['wearables', 'fitness'], price: 129, orig: 149, shape: 'watch', hue: 20, tags: ['fitness-tracking'], tagline: 'A screenless band for 24/7 training data.', blurb: 'Stride tracks strain, sleep and heart rate variability without a screen to distract you.', features: ['HRV and strain tracking', '14-day battery', 'Slide-on charger'], specs: { Battery: '14 days', Weight: '19 g' } },
  { name: 'Veloce Pace Watch', brand: 'veloce-labs', cats: ['wearables', 'fitness', 'outdoor'], price: 399, shape: 'watch', hue: 15, tags: ['gps', 'running'], score: [8.8, 8.3, 8.7, 8.6, 9.2, 9], tagline: 'A GPS running watch with dual-band accuracy.', blurb: 'Pace uses dual-band GPS for accurate tracks under trees and between buildings, and lasts three weeks.', features: ['Dual-band GPS', 'Offline maps', 'Training load and recovery', '21-day battery'], specs: { Battery: '21 days / 40 h GPS', Weight: '52 g' }, seller: 'seller2' },
  // Travel
  { name: 'Driftline Carry 35', brand: 'driftline', cats: ['travel'], price: 249, shape: 'backpack', hue: 210, tags: ['carry-on', 'backpack'], score: [8.7, 8.9, 9, 8.3, 8.8, 8.6], tagline: 'A 35 L backpack that opens like a suitcase.', blurb: 'Carry 35 clamshells fully open, has a lay-flat laptop compartment and fits every major carry-on sizer.', features: ['Clamshell opening', 'Lay-flat laptop sleeve', 'Hidden passport pocket', 'Recycled sailcloth'], specs: { Volume: '35 L', Weight: '1.4 kg', Dimensions: '55 × 35 × 20 cm' }, seller: 'seller3' },
  { name: 'Driftline Cube Set', brand: 'driftline', cats: ['travel'], price: 69, orig: 89, shape: 'cube', hue: 200, tags: ['packing-cubes'], tagline: 'Compression packing cubes with two zips.', blurb: 'A second zip squeezes each cube to about half its size — clothes in, air out.', features: ['Compression zip', 'Mesh vent panel', 'Set of three sizes'], specs: { Sizes: 'S, M, L', Material: 'Recycled ripstop' }, seller: 'seller3' },
  { name: 'Pocketwise Tag Tracker', brand: 'pocketwise', cats: ['travel', 'productivity'], price: 29, shape: 'tag', hue: 45, tags: ['tracker'], tagline: 'A card-thin tracker for wallets and luggage.', blurb: 'Tag slips into a wallet or luggage tag and works with both major phone tracking networks.', features: ['Works with iOS and Android networks', '2 mm thin', 'Rechargeable'], specs: { Battery: '5 months', Thickness: '2 mm' } },
  { name: 'Pocketwise Fold Charger 65', brand: 'pocketwise', cats: ['travel', 'office'], price: 59, shape: 'charger', hue: 40, tags: ['charger', 'gan'], tagline: 'A 65 W GaN charger with folding plug adapters.', blurb: 'One brick with swappable plug heads for four regions and three ports that share 65 W.', features: ['65 W GaN', 'Two USB-C, one USB-A', 'US, UK, EU, AU plugs'], specs: { Output: '65 W', Weight: '120 g' } },
  { name: 'Brightwater Pure Bottle', brand: 'brightwater-gear', cats: ['travel', 'outdoor', 'health-wellness'], price: 89, shape: 'bottle', hue: 190, tags: ['water-purification', 'uv'], score: [8.1, 8.5, 8.4, 7.8, 8, 8.2], tagline: 'A bottle that purifies water with UV light.', blurb: 'Press the cap and UV-C LEDs treat the water in 60 seconds, then again every few hours to keep the bottle fresh.', features: ['UV-C purification in 60 s', 'Self-cleaning mode', 'Insulated steel'], specs: { Capacity: '500 ml', Battery: '2 months' }, seller: 'seller3' },
  // Fitness
  { name: 'Veloce Form Bar', brand: 'veloce-labs', cats: ['fitness'], price: 249, shape: 'dumbbell', hue: 20, tags: ['strength', 'sensors'], score: [8.2, 8, 8.7, 7.9, 8.3, 8.1], tagline: 'A smart bar that counts reps and checks form.', blurb: 'Form Bar measures bar speed and path to count reps, flag form breakdown and suggest weights.', features: ['Rep and velocity tracking', 'Form feedback', 'Works with any plates'], specs: { Weight: '8 kg', Battery: '3 months' }, seller: 'seller2' },
  { name: 'Veloce Rollout Recovery Roller', brand: 'veloce-labs', cats: ['fitness', 'health-wellness'], price: 119, orig: 139, shape: 'roller', hue: 25, tags: ['recovery'], tagline: 'A vibrating foam roller with guided sessions.', blurb: 'Rollout adds five vibration levels to a firm roller and pairs with short guided recovery routines.', features: ['5 vibration levels', 'Guided routines', 'USB-C charging'], specs: { Battery: '3 h', Length: '33 cm' }, seller: 'seller2' },
  { name: 'Veloce Rowline Compact Rower', brand: 'veloce-labs', cats: ['fitness', 'smart-home'], price: 999, shape: 'rower', hue: 15, availability: 'preorder', tags: ['cardio'], tagline: 'A foldable water rower for small apartments.', blurb: 'Rowline folds upright to the footprint of a chair and uses a real water tank for smooth resistance.', features: ['Water resistance', 'Folds upright', 'Live power and stroke rate'], specs: { Footprint: '55 × 55 cm folded', 'Max user weight': '150 kg' }, seller: 'seller2' },
  // Kitchen
  { name: 'Tallow Precision Kettle', brand: 'tallow-kitchen', cats: ['kitchen'], price: 139, shape: 'kettle', hue: 340, tags: ['coffee', 'tea'], score: [8.5, 9, 8.8, 8.1, 8.2, 8.4], tagline: 'A pour-over kettle with one-degree control.', blurb: 'Set the exact temperature with a real dial, hold it for an hour, and pour with a gooseneck spout.', features: ['±1 °C temperature dial', '60-minute hold', 'Gooseneck spout', 'Brew timer'], specs: { Capacity: '0.9 L', Power: '1200 W' }, seller: 'seller2' },
  { name: 'Tallow Sear Probe', brand: 'tallow-kitchen', cats: ['kitchen'], price: 79, orig: 99, shape: 'probe', hue: 350, tags: ['thermometer', 'wireless'], tagline: 'A wireless meat probe with five sensors.', blurb: 'Five sensors along the probe estimate the true core temperature and predict when dinner is ready.', features: ['Five internal sensors', 'Rest-time prediction', '50 m range'], specs: { Battery: '30 h', 'Max temperature': '300 °C' }, seller: 'seller2' },
  { name: 'Hearth & Byte Countertop Oven Eye', brand: 'hearth-and-byte', cats: ['kitchen', 'ai-gadgets', 'smart-home'], price: 599, shape: 'oven', hue: 20, tags: ['smart-oven', 'camera'], score: [8, 8.8, 8.2, 7.4, 8.4, 7.9], tagline: 'A countertop oven with a camera that watches the browning.', blurb: 'Oven Eye recognizes common foods, sets the program and stops when toast or roast looks right.', features: ['Food recognition camera', 'Air fry, bake, roast, dehydrate', 'Browning control'], specs: { Capacity: '25 L', Power: '1800 W' } },
  { name: 'Hearth & Byte Scale Plus', brand: 'hearth-and-byte', cats: ['kitchen', 'health-wellness'], price: 49, shape: 'scale', hue: 10, tags: ['nutrition'], tagline: 'A kitchen scale that logs nutrition as you cook.', blurb: 'Weigh each ingredient and the app builds the recipe\'s nutrition label for you.', features: ['0.1 g precision', 'Recipe logging', 'Tare per ingredient'], specs: { Capacity: '5 kg', Battery: '6 months' } },
  // Office
  { name: 'Orbital Float Monitor Arm', brand: 'orbital-desk', cats: ['office', 'desk-setup'], price: 179, shape: 'arm', hue: 220, tags: ['ergonomics'], score: [8.4, 8.7, 8.9, 8.2, 8, 8.2], tagline: 'A gas-spring monitor arm with a built-in dock.', blurb: 'Float holds up to 32" and hides a USB-C dock in its base, so one cable goes to your laptop.', features: ['Gas spring for up to 9 kg', 'USB-C dock in the base', 'Cable channels'], specs: { 'Max load': '9 kg', Ports: 'HDMI, 3 × USB-A, Ethernet' }, seller: 'seller1' },
  { name: 'Orbital Glow Monitor Light', brand: 'orbital-desk', cats: ['office', 'desk-setup', 'smart-lighting'], price: 89, orig: 109, shape: 'lamp', hue: 230, tags: ['lighting', 'ergonomics'], tagline: 'A screen light bar that lights the desk, not the screen.', blurb: 'Asymmetric optics throw light onto your desk without glare on the monitor, with a backlight for the wall.', features: ['No screen glare', 'Wall backlight', 'Wireless dial'], specs: { Brightness: '600 lx', Power: 'USB-C' }, seller: 'seller1' },
  { name: 'Quillwork Slate Notebook', brand: 'quillwork', cats: ['office', 'productivity'], price: 399, shape: 'tablet', hue: 45, tags: ['e-paper', 'focus'], score: [8.9, 9.3, 9.1, 8, 8.6, 9.2], tagline: 'An e-paper notebook that feels like paper.', blurb: 'Slate has a textured 10.3" e-paper display, a battery-free pen and nothing else to distract you.', features: ['10.3" e-paper display', 'Handwriting to text', 'Two-week battery', 'No apps, no notifications'], specs: { Weight: '360 g', Battery: '2 weeks' } },
  { name: 'Quillwork Tactile Keyboard', brand: 'quillwork', cats: ['office', 'keyboards'], price: 169, shape: 'keyboard', hue: 40, tags: ['mechanical', 'wireless'], tagline: 'A low-profile mechanical keyboard in aluminium.', blurb: 'Quiet tactile switches, a CNC aluminium case and three-device switching.', features: ['Low-profile tactile switches', 'Aluminium case', 'Multi-device switching', 'Hot-swappable'], specs: { Layout: '75%', Battery: '2 months' } },
  { name: 'Quillwork Focus Timer', brand: 'quillwork', cats: ['productivity', 'office'], price: 39, shape: 'timer', hue: 50, tags: ['focus', 'pomodoro'], tagline: 'A flip timer for focused work sessions.', blurb: 'Flip it to the side with 25, 45 or 60 minutes on top and it starts; a gentle chime ends the session.', features: ['Flip-to-start', 'Silent mode', 'No app'], specs: { Battery: '6 months' } },
  // Outdoor
  { name: 'Ridgeback Sunpack 20', brand: 'ridgeback-outdoor', cats: ['outdoor', 'eco-tech', 'travel'], price: 149, shape: 'solar', hue: 45, tags: ['solar', 'power-bank'], score: [8.3, 8.1, 8.6, 8.5, 8, 8.4], tagline: 'A folding solar panel with a 20,000 mAh battery.', blurb: 'Sunpack charges its own battery during the day and your devices at night, and folds to paperback size.', features: ['21 W folding solar panel', '20,000 mAh battery', 'USB-C 45 W output'], specs: { Weight: '680 g', Output: '45 W' }, seller: 'seller3' },
  { name: 'Ridgeback Beacon Lantern', brand: 'ridgeback-outdoor', cats: ['outdoor'], price: 79, orig: 95, shape: 'lantern', hue: 40, tags: ['camping', 'lighting'], tagline: 'A camp lantern that doubles as an emergency beacon.', blurb: 'Beacon gives soft camp light, a red night mode and an SOS strobe visible for kilometres.', features: ['500 lm warm light', 'SOS strobe', 'Power bank output', 'IP67'], specs: { Battery: '100 h low mode', Weight: '310 g' }, seller: 'seller3' },
  { name: 'Ridgeback Trailmate Navigator', brand: 'ridgeback-outdoor', cats: ['outdoor', 'travel'], price: 349, shape: 'phone', hue: 100, tags: ['gps', 'satellite'], tagline: 'A satellite messenger with offline maps.', blurb: 'Trailmate sends messages and your location over satellite when there is no signal, and shows topo maps offline.', features: ['Two-way satellite messaging', 'Topographic maps', 'SOS button'], specs: { Battery: '14 days tracking', Weight: '180 g' }, seller: 'seller3' },
  { name: 'Petrichor Solar Speaker', brand: 'petrichor-tech', cats: ['eco-tech', 'audio', 'outdoor'], price: 99, shape: 'speaker', hue: 120, tags: ['solar', 'repairable'], tagline: 'A repairable speaker that tops up in the sun.', blurb: 'Made from recycled ocean plastic with screws instead of glue, and a solar panel that extends playtime indefinitely outdoors.', features: ['Solar top-up', 'Screw-together repairable design', 'Recycled plastic shell'], specs: { Battery: '24 h', Weight: '520 g' } },
  { name: 'Petrichor Charge Garden', brand: 'petrichor-tech', cats: ['eco-tech', 'smart-home'], price: 129, availability: 'crowdfunding', shape: 'solar', hue: 110, tags: ['solar', 'crowdfunding'], tagline: 'A window solar charger shaped like a planter.', blurb: 'Stick Charge Garden to a window and it banks solar energy for phones, with a small herb planter on top.', features: ['Window-mount solar cells', 'Built-in planter', '10,000 mAh battery'], specs: { Output: '20 W' } },
  // Automotive
  { name: 'Voltra Duo Dash Cam', brand: 'voltra-motive', cats: ['automotive'], price: 199, orig: 239, shape: 'dashcam', hue: 210, tags: ['dash-cam', '4k'], score: [8.4, 8, 8.6, 8.7, 8.5, 8.3], tagline: 'A front-and-rear 4K dash cam with parking mode.', blurb: 'Duo records both directions, keeps watch while parked and saves incident clips to your phone automatically.', features: ['4K front, 1080p rear', 'Parking mode', 'Auto clip saving', 'Supercapacitor for heat'], specs: { Resolution: '3840 × 2160', Storage: 'microSD up to 256 GB' } },
  { name: 'Voltra MagCharge Mount', brand: 'voltra-motive', cats: ['automotive'], price: 69, shape: 'mount', hue: 200, tags: ['charger', 'magnetic'], tagline: 'A cooled magnetic phone mount with 15 W charging.', blurb: 'A small fan keeps the phone cool while it charges on the dash in summer.', features: ['15 W magnetic charging', 'Active cooling', 'One-hand mount'], specs: { Output: '15 W' } },
  { name: 'Voltra Air Pump Mini', brand: 'voltra-motive', cats: ['automotive', 'outdoor'], price: 59, shape: 'pump', hue: 190, tags: ['tire-inflator'], tagline: 'A pocket tire inflator that stops at the set pressure.', blurb: 'Set the pressure, attach it and walk away — it stops automatically, for car, bike or ball.', features: ['Auto-stop at target pressure', 'Car, bike and ball modes', 'LED light'], specs: { 'Max pressure': '150 PSI', Weight: '350 g' } },
  // Health
  { name: 'Fernhill Drift Sleep Headband', brand: 'fernhill-wellness', cats: ['health-wellness', 'wearables'], price: 199, shape: 'headband', hue: 260, tags: ['sleep'], score: [8, 8.6, 8.2, 7.5, 8.3, 7.9], tagline: 'A soft headband that plays sound timed to your sleep.', blurb: 'Drift senses when you fall asleep and fades audio out, with flat speakers you can sleep on.', features: ['Flat side-sleeper speakers', 'Sleep-onset detection', 'Wind-down soundscapes'], specs: { Battery: '12 h', Material: 'Washable knit' } },
  { name: 'Fernhill Clear Air Monitor', brand: 'fernhill-wellness', cats: ['health-wellness', 'smart-home'], price: 119, orig: 149, shape: 'hub', hue: 150, tags: ['air-quality', 'sensors'], tagline: 'An air monitor that tells you when to open a window.', blurb: 'Clear tracks CO₂, particles and humidity and glows amber when a room needs fresh air.', features: ['CO₂ NDIR sensor', 'PM2.5 sensor', 'Color status light', 'Works offline'], specs: { Sensors: 'CO₂, PM2.5, humidity, temperature', Battery: '2 weeks' } },
]

// Products still in the review workflow (owned by demo sellers).
export const workflowProducts = [
  { name: 'Halden Arc Kids', brand: 'halden-audio', cats: ['audio', 'headphones'], price: 89, shape: 'headphones', hue: 330, tags: ['kids', 'volume-limited'], seller: 'seller1', state: 'submitted', tagline: 'Volume-limited headphones sized for kids.', blurb: 'Arc Kids caps volume at 85 dB and uses a bendable headband that survives backpacks.', features: ['85 dB volume limit', 'Bendable headband', 'Share port'], specs: { Weight: '160 g' } },
  { name: 'Lumen & Oak Dawn Alarm', brand: 'lumen-and-oak', cats: ['smart-home', 'smart-lighting', 'health-wellness'], price: 149, shape: 'lamp', hue: 30, tags: ['sunrise-alarm'], seller: 'seller1', state: 'under_review', tagline: 'A sunrise alarm clock in oak and linen.', blurb: 'Dawn brightens gradually over 30 minutes before your alarm, then plays soft birdsong.', features: ['30-minute sunrise', 'Linen diffuser', 'No app required'], specs: { Brightness: '300 lm' } },
  { name: 'Veloce Stride Insoles', brand: 'veloce-labs', cats: ['fitness', 'wearables'], price: 179, shape: 'insole', hue: 20, tags: ['running', 'sensors'], seller: 'seller2', state: 'changes_requested', message: 'Please upload higher-quality lifestyle images and add the battery life to the specifications.', tagline: 'Pressure-sensing insoles for running form.', blurb: 'Stride Insoles map foot strike and cadence in real time and coach you through the watch.', features: ['Pressure mapping', 'Cadence coaching'], specs: { Weight: '40 g per insole' } },
  { name: 'Driftline Sling 6', brand: 'driftline', cats: ['travel'], price: 79, shape: 'backpack', hue: 190, tags: ['sling'], seller: 'seller3', state: 'draft', tagline: 'A 6 L sling for passport, phone and camera.', blurb: 'A small sling that sits flat against your back with a quick-access camera pocket.', features: ['Quick-access pocket', 'Hidden back zip'], specs: { Volume: '6 L' } },
  { name: 'Tallow Smart Salt Grinder', brand: 'tallow-kitchen', cats: ['kitchen'], price: 39, shape: 'grinder', hue: 0, tags: ['gadget'], seller: 'seller2', state: 'rejected', message: 'This duplicates an existing listing and the product URL does not load. Please contact us if this is a new model.', tagline: 'A grinder that counts every pinch.', blurb: 'Logs how much salt you add to each meal.', features: ['Pinch counter'], specs: {} },
  { name: 'Ridgeback Pocket Stove', brand: 'ridgeback-outdoor', cats: ['outdoor'], price: 99, shape: 'lantern', hue: 20, tags: ['camping', 'cooking'], seller: 'seller3', state: 'scheduled', tagline: 'A 70 g stove with a piezo igniter.', blurb: 'Pocket Stove boils half a litre in three minutes and folds smaller than a lighter case.', features: ['Piezo igniter', 'Wind shield', '70 g'], specs: { Weight: '70 g', Output: '2.8 kW' } },
]

export const collections = [
  { title: 'Best AI Gadgets of the Year', editorial: true, featured: true, description: 'The on-device AI products our editors actually kept using after the review period ended.', products: ['Tessellate Lingo One', 'Parsec Pip Desk Robot', 'Tessellate Minutes', 'Hearth & Byte Countertop Oven Eye', 'Parsec Rover Home Assistant'] },
  { title: 'The Calm Desk', editorial: true, featured: true, description: 'Everything for a quiet, focused, cable-free workspace.', products: ['Orbital Float Monitor Arm', 'Orbital Glow Monitor Light', 'Quillwork Slate Notebook', 'Quillwork Tactile Keyboard', 'Quillwork Focus Timer', 'Lumen & Oak Solstice Lamp'] },
  { title: 'Carry-On Essentials', editorial: true, featured: true, description: 'Our tested kit for traveling with one bag.', products: ['Driftline Carry 35', 'Driftline Cube Set', 'Pocketwise Fold Charger 65', 'Pocketwise Tag Tracker', 'Tessellate Lingo One', 'Brightwater Pure Bottle'] },
  { title: 'Smart Home Without the Cloud', editorial: true, featured: true, description: 'Devices that keep working locally when the internet goes down.', products: ['Nimbus Keystone Lock', 'Nimbus Sense Hub', 'Nimbus Watchpost Camera', 'Fernhill Clear Air Monitor', 'Lumen & Oak Halo Strip'] },
  { title: 'Crowdfunding & Coming Soon', editorial: true, featured: false, description: 'Projects we are watching before they ship.', products: ['Petrichor Charge Garden', 'Tessellate Glance Glasses', 'Parsec Rover Home Assistant', 'Veloce Rowline Compact Rower'] },
  { title: 'Weekend Off-Grid', editorial: true, featured: false, description: 'Power, light and navigation for two nights outside.', products: ['Ridgeback Sunpack 20', 'Ridgeback Beacon Lantern', 'Ridgeback Trailmate Navigator', 'Cinder Ember Speaker', 'Brightwater Pure Bottle'] },
  { title: 'Gifts Under $100', editorial: true, featured: true, description: 'Great gadgets that do not break the budget.', products: ['Moonforge Tide Controller', 'Pocketwise Tag Tracker', 'Quillwork Focus Timer', 'Tallow Sear Probe', 'Voltra Air Pump Mini', 'Hearth & Byte Scale Plus', 'Petrichor Solar Speaker'] },
  { title: 'Creator Starter Kit', editorial: true, featured: false, description: 'Camera, audio and lighting for your first videos.', products: ['Grainfield F1 Compact', 'Kestrel Slate Gimbal', 'Halden Studio Monitor 5', 'Arclight Stream Deck Mini', 'Orbital Glow Monitor Light'] },
  { title: 'Better Sleep Tech', editorial: true, featured: false, description: 'Tools that help you fall asleep and wake up rested.', products: ['Sable Loop Ring', 'Fernhill Drift Sleep Headband', 'Fernhill Clear Air Monitor', 'Lumen & Oak Solstice Lamp'] },
  { title: 'Home Gym, Small Apartment', editorial: true, featured: false, description: 'Compact training gear that stores away.', products: ['Veloce Form Bar', 'Veloce Rollout Recovery Roller', 'Veloce Rowline Compact Rower', 'Sable Stride Band', 'Veloce Pace Watch'] },
  // user collections
  { title: 'My Dream Desk Setup', owner: 'user1', visibility: 'public', description: 'Slowly building the perfect desk.', products: ['Orbital Float Monitor Arm', 'Quillwork Tactile Keyboard', 'Orbital Glow Monitor Light', 'Halden Studio Monitor 5'] },
  { title: 'Japan trip 2027', owner: 'user1', visibility: 'private', description: 'Things to buy before the trip.', products: ['Tessellate Lingo One', 'Driftline Carry 35', 'Pocketwise Fold Charger 65'] },
  { title: 'Audio wishlist', owner: 'user2', visibility: 'public', description: 'Headphones and speakers I want to try.', products: ['Halden Arc Pro', 'Cinder Ember Speaker', 'Halden Pebble Buds'] },
]

export const deals = [
  { product: 'Halden Arc Pro', price: 299, title: 'Launch-week price', days: [-2, 10] },
  { product: 'Kestrel Swift Drone', price: 579, title: 'Fly Kit bundle discount', days: [-5, 7], code: 'SWIFTFLY' },
  { product: 'Tessellate Lingo One', price: 219, title: 'Travel season offer', days: [-1, 14] },
  { product: 'Nimbus Keystone Lock', price: 229, title: 'Smart lock week', days: [-3, 4] },
  { product: 'Moonforge Tide Controller', price: 69, title: 'Flash deal', days: [-0.5, 1.5] },
  { product: 'Quillwork Slate Notebook', price: 349, title: 'Back to work', days: [3, 17] },
  { product: 'Driftline Carry 35', price: 199, title: 'Last summer sale', days: [-30, -2] },
]

export const articles = [
  { title: 'Hands-on: the offline translator that actually works on a plane', type: 'hands_on', cats: ['ai-gadgets', 'travel'], products: ['Tessellate Lingo One'], days: -1, excerpt: 'We took Lingo One through three airports and a mountain village with no signal. Here is what worked and what did not.' },
  { title: 'The best noise-cancelling headphones for long flights', type: 'buying_guide', cats: ['audio', 'travel'], products: ['Halden Arc Pro', 'Halden Pebble Buds'], days: -3, excerpt: 'Comfort matters more than spec sheets after hour six. Our picks for long-haul listening.' },
  { title: 'Review: Kestrel Swift is the drone to beat under 250 g', type: 'review', cats: ['photography', 'drones'], products: ['Kestrel Swift Drone'], days: -4, excerpt: 'A 1-inch sensor in a registration-free drone changes what a travel drone can do.' },
  { title: 'How to build a smart home that works without the internet', type: 'how_to', cats: ['smart-home'], products: ['Nimbus Sense Hub', 'Nimbus Keystone Lock'], days: -6, excerpt: 'Local control, Matter and Thread explained, plus the devices we trust.' },
  { title: 'Roundup: 12 desk upgrades under $200', type: 'roundup', cats: ['office', 'desk-setup'], products: ['Orbital Float Monitor Arm', 'Orbital Glow Monitor Light', 'Quillwork Focus Timer'], days: -8, excerpt: 'Small changes that make a big difference to a long working day.' },
  { title: 'Interview: why Parsec built a robot with a physical camera shutter', type: 'interview', cats: ['ai-gadgets'], products: ['Parsec Pip Desk Robot'], days: -10, excerpt: 'The founders on privacy by design and why their robot has no cloud account.' },
  { title: 'Hall-effect sticks explained: the end of controller drift?', type: 'news', cats: ['gaming'], products: ['Moonforge Tide Controller'], days: -12, excerpt: 'Magnetic sensors are spreading across controllers. Here is how they work.' },
  { title: 'Buying guide: smart rings versus fitness bands', type: 'buying_guide', cats: ['wearables', 'health-wellness'], products: ['Sable Loop Ring', 'Sable Stride Band'], days: -14, excerpt: 'Which form factor fits your sleep and training goals better?' },
  { title: 'Review: Grainfield F1 brings dials back to pocket cameras', type: 'review', cats: ['photography'], products: ['Grainfield F1 Compact'], days: -16, excerpt: 'A camera that makes you slow down — in a good way.' },
  { title: 'Packing light: our one-bag travel system', type: 'how_to', cats: ['travel'], products: ['Driftline Carry 35', 'Driftline Cube Set', 'Pocketwise Fold Charger 65'], days: -19, excerpt: 'How our editors pack for two weeks with a single carry-on.' },
  { title: 'Solar gadgets that are worth it (and some that are not)', type: 'roundup', cats: ['eco-tech', 'outdoor'], products: ['Ridgeback Sunpack 20', 'Petrichor Solar Speaker', 'Petrichor Charge Garden'], days: -22, excerpt: 'We measured real-world charging so you do not have to.' },
  { title: 'Coming up: what we expect from connected kitchens next year', type: 'news', cats: ['kitchen'], products: ['Hearth & Byte Countertop Oven Eye'], days: 2, status: 'scheduled', excerpt: 'Cameras, sensors and fewer apps.' },
]
